### ISSUE TITLE
Account Creation: Cancelling

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruAndroid#17]
On the Account Creation Screen, if you tap Cancel, it pops up a box asking if you are sure you want to cancel. The Yes and No operate oppositely of how the user expects. The Yes should cancel. In addition, the text gets cut off. It should read, "Are you sure you want to cancel account creation? This will discard any information you have entered."

App Version: 1.0
Android 8.0
Nexus 5x

**Comment by supersun1** [comment]
resolved! :)
